name: Deploy to GitHub Pages

on:
  push:
    branches: 
      - master
      - deploy-action

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    
    - uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Invoke Webpack build
      run: |
        yarn install .
        yarn run build
    - name: Invoke Deployment
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build
      uses: JamesIves/github-pages-deploy-action@3.6.1